### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by sg-kcs** [earthquake/UniversalDVC#2]
On the server side when initiating -s, I get as far as ...

[*] Setting up server socket
[*] Listening on: 127.0.0.1:31337

but it goers no further. Client side I am somewhat confused whether it should be listening or trying to connect..the default client condition is mode 0 listen (?) yet if both are listening no one is connecting? Either way the server goes no further than as you see above. What am I doing wrong?

thanks...

**Comment by earthquake** [comment]
Please read the README attached to the tool, it has some figures as well to explain the different situations. If you want to use it as a simple port forward, then your need to use the UDVC-Server.exe in client mode, specifying the port (-p PORT). In this case when you connect to the RDP client's 31337 port, everything will be sent to the Terminal Server's port, which was specified in the argument.

The figures will help understand this.

**Comment by Bizzle-Dapp** [comment]
Hey @earthquake, 

Nice repo, however i'm having something of a similar issue above. 

I have written a little command line app that i was hoping would be able to take advantage of the connection this opened on the RDP channel in order to transmit information between the RDP active session window out into another console application running locally. 

The code behind states: 
```
bSucc = WriteFile(handles->hRDP, readBuf, dw, &dwWritten, &Overlapped);
```
As the executed method when no error is thrown. Where are these files written? I have only managed to connect to the .exe when accessing it through 127.0.0.1 locally on the same machine, otherwise there it doesn't seem to hear any data being transmitted from the machine outside the rdp connection? The same applies in reverse as well - i have tried to listen using a TcpClient connection on 127.0.0.1 using the default port of 31337 but nothing out of the RDP session is heard. 

Are you able to provide a simplistic diagram detailing utilising the TCP client/server setup to transmit data back and forth? Or perhaps the process of accessing the Named Pipe the application creates so that both Client and Server are able to transmit information streams through said pipe? 

Any further information surrounding this would be deeply appreciated. 

Thanks, 
B_D
