### ISSUE TITLE
UDVC-Server.x64.exe crashing after first message sent

### ISSUE THREAD

**Issue by Steffen-MLR** [earthquake/UniversalDVC#3]
UDVC-Server.x64.exe
Universal Dynamic Virtual Channel server application

[*] Setting up server socket
[*] Listening on: 127.0.0.1:31337
[+] Client connected
[*] Starting thread RsWc
[*] Starting thread RcWs
[*] Waiting for threads to exit...
[-] [RsWc] recv() failed with error 0, exiting thread...

Hey man,

I tried to send a string via c# sockets (Type= Stream, TCP). This works excatly one time, and afterwards your app is shutting down, after a few seconds even the mstsc crashes.
I could not find any Information in your Documentation about what Type of Data I can send through the DVC. I use the Client in Listening mode too.

looking forward to your reply!

**Comment by earthquake** [comment]
Hello @Steffen-MLR,

The UDVC is a generic tool, does not restart itself or handles multiple connections. After you disconnect, the thread exits and that is it, you need to restart the tool. 
"recv() failed with error 0" - means that the connection was closed on either side. Probably the connection was closed by the service that you connected to on the server side.

Regarding the crash, that must be a UAF bug or something like that. It should be fixed, if you can share the setup and tool that you use, I might be able to fix it.

Thanks.

**Comment by Steffen-MLR** [comment]
My Code for sending:
`Socket soc = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);`
`IPAddress ipAdd = IPAddress.Parse("127.0.0.1");`
`int port = 31337;`
`IPEndPoint remoteEP = new IPEndPoint(ipAdd, port);`
`soc.Connect(remoteEP);`
`byte[] byData = Encoding.ASCII.GetBytes(info);`
`soc.Send(byData);`
// even without these two, the App is crashing
`soc.Disconnect(false); `
`soc.Close();`

My Code for Receiving:
`Socket soc = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);`
`IPAddress ipAdd = IPAddress.Parse("127.0.0.1");`
`int port = 31337;`
`IPEndPoint remoteEP = new IPEndPoint(ipAdd, port);`
`soc.Connect(remoteEP);`
`byte[] buffer = new byte[1024];`
`int iRx = soc.Receive(buffer);`
`char[] chars = new char[iRx];`
`Decoder d = Encoding.UTF8.GetDecoder();`
`int charLen = d.GetChars(buffer, 0, iRx, chars, 0);`
`Console.WriteLine(new string(chars));`

[Program.txt](https://github.com/earthquake/UniversalDVC/files/4585048/Program.txt)

Here is my Program.cs (as txt). I hope you can help me with this!

**Comment by earthquake** [comment]
What are the operating systems and how do you use the command on the server, what are the settings for the dll?

**Comment by Steffen-MLR** [comment]
DLL:
"Name"="{3C8458A3-2EBE-4840-BB07-3BA5BF810588}"
"namedpipename"="\\\\.\\pipe\\UDVC_default"
"ip"="127.0.0.1"
"port"="31337"
"mode"=dword:00000000
"enabled"=dword:00000001

EXE:
UDVC-Server.x64.exe
(no Parameters)

Client: Windows 10 Pro 64 Bit
Server: Windows Server 2019 Datacenter 64 Bit

**Comment by earthquake** [comment]
Compiled UDVC from source, compiled your source (program.txt) as .NET, debug for Any CPU. Connected to the server (different arch for server, but still), started UDVC-Server.exe with no parameters then run your code on both sides with "receive" and "send" in all 4 permutations. UDVC did not crash, but your tool threw many exceptions about the socket being lost/closed.

Will do a few mods in the code, but since I cannot reproduce the crash in the .dll I am not sure that  your issue will be fixed.

**Comment by Steffen-MLR** [comment]
looking forward to your changes!

I will once again test it on my system. Which architechture did you use on the server side?

**Comment by earthquake** [comment]
Rearranged a few things in both components, please find it updated under the release section.
Can you please test it with the new binaries and let me know? Hopefully this will solve your problem.

If not, can you please let me know and we could figure out?
There could be two ways to solve this:
- I send you a pdb file that you can use with windbg to debug where the UAF bug is
- You compile yours with Visual Studio and use that pdb

If we have the buggy line, I can figure out the rest.

Re architecture: Win2k8 SP2 x86 for server, that's what I have installed atm.

**Comment by Steffen-MLR** [comment]
With your new Release I get this Error:

[*] Setting up server socket
[*] Listening on: 127.0.0.1:31337
[+] Client connected
[*] Starting thread RsWc
[*] Starting thread RcWs
[*] Waiting for threads to exit...
[-] [RsWc] socket closed, exiting thread...
[-] [RcWs] ReadFile()/WaitForSingleObject() error: 996

May I ask, should the UDVC Connection stay established? Or is this the normal behavior? Because I then can implement it this way.

**Comment by earthquake** [comment]
Most importantly, does your remote desktop client still crash?

Based in the log, this is expected behaviour. The connection was closed (client disconnected from 127.0.0.1:31337) so the RDP channel was closed as well - last two lines.

**Comment by earthquake** [comment]
No answer for almost a month, could not reproduce the issue so it is considered fixed -> closed.

**Comment by 0xArt3mis** [comment]
Hi, 

it is an old issue but it is still not fixed. 

I get the same error: 
[-] [RcWs] ReadFile()/WaitForSingleObject() error: 996

First connection stays established but new connections are not forwarded over the channel. 
By any chance would this be possible to support handling multiple connections?

I need to restart the tool everytime to obtain commands from the C2 server, since the first connection stays established. 

I have tested it with a C2 with a random sleep / jitter to obtain commands using the channel. But this is only working for the first request. Executing an Agent on the target system (UDVC-Server) to connect to 127.0.0.1:443 UDVC was working for the first request but blocking all further requests to the C2 server. 

Also using this tool it was not possible to route traffic from the client side to the server side, only from the server to the client. SocksOverRDP was working from client side to server side. 

I have tried to create an SSH Remote Port Forwarding Tunnel from the client side to a dedicated Kali Linux system. then I used proxychains to route nmap scan through the connection, this was not working with UDVC but it was working with SocksOverRDP. What exactly is the difference here?

**Comment by earthquake** [comment]
Hi @CT-H00K,

The error that you have is likely happening because of the behaviour of the tool and they way how you use it.
The tool is kind of like netcat, over RDP. So when a connection closes on any of the sides, it stops working and needs to be restarted. This is more like a proof of concept to show what could be done over RDP. The tool is open source, I hoped others will be interested to take over the project and develop stuff for it. Pull requests are welcome.

SocksOverRDP, like it is in the name, is creating a Socks proxy over RDP, the different is that, that works as intended, listens for connections and spawns new threads when needed. UDVC was not created for that reason. I would recommend SocksOverRDP for future use.
